---
sidebar: sidebar 
permalink: concept-digital-wallet.html 
keywords: digital wallet, bluexp digital wallet, licensing, licenses, services, supported services 
summary: 'A carteira digital da BlueXP  permite que você gerencie e monitore as licenças BlueXP  adquiridas na NetApp (BYOL), nas assinaturas do marketplace da BlueXP  e no NetApp Keystone.' 
---
= Saiba mais sobre a carteira digital BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A carteira digital da BlueXP  permite que você gerencie e monitore as licenças BlueXP  adquiridas na NetApp (BYOL), assinaturas do mercado de serviços de dados da BlueXP  (incluindo NetApp Cloud Volumes ONTAP) e NetApp Keystone.



== Como as licenças e assinaturas são exibidas na carteira digital

Ambas as licenças e assinaturas são exibidas automaticamente na carteira digital quando a conta BlueXP  usada para assinar também é uma conta do site de suporte da NetApp. Se você usou uma conta do BlueXP  que não está associada à sua conta do site de suporte da NetApp (NSS), precisará adicionar e atualizar manualmente as licenças e não verá a alteração de uso, capacidade e outros detalhes.


NOTE: Você precisa ter implantado um conetor para visualizar as informações de assinatura na carteira digital. Um conetor também é necessário para visualizar as licenças de nós para o Cloud Volumes ONTAP.

Enquanto isso, o BlueXP  consulta automaticamente o serviço de licenciamento da NetApp para obter detalhes sobre as licenças associadas à sua conta do site de suporte da NetApp. Se não houver erros, o BlueXP  adiciona automaticamente as licenças à carteira digital.

Se o BlueXP  não conseguir adicionar a licença, você precisará adicioná-la manualmente à carteira digital. Por exemplo, se sua conta de usuário do BlueXP  não estiver associada à conta do site de suporte da NetApp, você precisará adicionar as licenças por conta própria.

Depois de adquirir uma licença do seu representante de vendas da NetApp, a NetApp envia-lhe um e-mail com o número de série e os detalhes de licenciamento adicionais. Você precisará desse número de série para adicionar ou atualizar a respetiva licença na carteira digital.

https://docs.netapp.com/us-en/bluexp-setup-admin/task-adding-nss-accounts.html["Saiba como adicionar sua conta do site de suporte da NetApp às credenciais de usuário do BlueXP "^].



== Serviços compatíveis

A carteira digital BlueXP  permite-lhe gerir licenças e subscrições para os seguintes serviços:

* https://docs.netapp.com/us-en/bluexp-backup-recovery/index.html["Backup e recuperação"^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^]
* https://docs.netapp.com/us-en/bluexp-disaster-recovery/index.html["Recuperação de desastres"^] (Apenas BYOL)
* https://docs.netapp.com/us-en/bluexp-ransomware-protection/index.html["Proteção contra ransomware"^]
* https://docs.netapp.com/us-en/bluexp-ontap-onprem/index.html["Clusters ONTAP no local"^]
* https://docs.netapp.com/us-en/bluexp-tiering/index.html["Disposição em camadas"^]

